### ISSUE TITLE
Can't Authenticate

### ISSUE THREAD

**Issue by ilovefreesw** [lewangdev/youtube-drive#3]
![image](https://user-images.githubusercontent.com/77317006/172631698-fa0d3f46-f337-48ae-ad56-a0ed8f74ffbc.png)

Any idea how to fix this ?

**Comment by lewangdev** [comment]
Thanks for reporting. I will check the new google validation rules.

**Comment by ilovefreesw** [comment]
I figured it out. Sorry... my application in GCP was set to "Internal" and that's why it was happening. I change the application type to "External" and then it worked. Thanks anyway.
