### ISSUE TITLE
How to upload google drive to youtube

### ISSUE THREAD

**Issue by Un-0wn** [lewangdev/youtube-drive#4]
Add a feature to this, that we can upload directly to YouTube from Google Drive. without using your bandwidth

**Comment by Th4Park** [comment]
And if you made the script in php, then you have a benefit that you can add all the advanced features as well. such as

telegram to youtube
torrent to youtube
ets.

**Comment by lewangdev** [comment]
The main functions of [youtube-drive](https://github.com/lewangdev/youtube-drive) are encoding and decoding.  Uploading file to youtube I use [youtube-upload](https://github.com/tokland/youtube-upload.git) repo.

**Comment by lewangdev** [comment]
> The main functions of [youtube-drive](https://github.com/lewangdev/youtube-drive) are encoding and decoding. Uploading file to youtube I use [youtube-upload](https://github.com/tokland/youtube-upload.git) repo.

[youtube-drive](https://github.com/lewangdev/youtube-drive) is a personal project and for demo and testing only. No more product requests would be accepted. Thanks.
