### ISSUE TITLE
Add optional encrypt/decrypt step

### ISSUE THREAD

**Issue by gongyisheng** [lewangdev/youtube-drive#8]
Encrypt video with user defined private key to make it only accessible to the owner after uploading to youtube.
I can help to contribute a PR

**Comment by lewangdev** [comment]
Nice idea! Can't wait to use the new feature of your contribution. 😀

**Comment by lewangdev** [comment]
Shocked by your development speed on PR #9. I will test it immediately, it is a toy and every contribution I want to merge as soon as possible
